version: '2'

# launch: docker-compose up --build -d

services:
  CertStreamMonitor:
    image: certstreammonitor
    container_name: certstreammonitor
    build: ./
    #tty: true
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf